project_id = "bpiruplrfnnthiugvgai"

[functions.chat-proxy]
verify_jwt = false

[functions.pdf-upload]
verify_jwt = false

[functions.pdf-delete]
verify_jwt = false

[functions.pdf-chat]
verify_jwt = false